CREATE TABLE IF NOT EXISTS musica (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    artista VARCHAR(150) NOT NULL
    );

INSERT INTO musica (nome, artista)
VALUES ('Happy', 'Williams');