CREATE TABLE IF NOT EXISTS jogador (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    numero INT NOT NULL,
    dtNasc DATE NOT NULL,
    sexo VARCHAR(20) NOT NULL,
    time VARCHAR(100) NOT NULL,
    posicao VARCHAR(50) NOT NULL,
    pe VARCHAR(20) NOT NULL,
    caracteristicas VARCHAR(500)
    );

CREATE TABLE IF NOT EXISTS times (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL
    );

INSERT INTO times (nome) VALUES
    ('Corinthians'),
    ('Santos'),
    ('São Paulo'),
    ('Palmeiras'),
    ('Flamengo'),
    ('Vasco'),
    ('Fluminense'),
    ('Botafogo'),
    ('Cruzeiro'),
    ('Atlético-MG'),
    ('Atlético-PR');